language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: surge
  project: ./
  domain: SnapTrails.surge.sh
script:
  - npm run build
  - npm start
addons:
  apt:
    update: true
